
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team01-f23-6pm-4
owner: ucsb-cs156-f23
repo_name: team01-f23-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"Ally-READMEFixes","number":30,"title":"READme fixes","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/30"},{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"Ally-Tide-Controller","number":28,"title":"Add Tide Controller and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/28"},{"author":{"id":"U_kgDOBclckQ","is_bot":false,"login":"allychu","name":""},"headRefName":"Ally-Tide","number":27,"title":"Add Tide Service and Tests","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/27"},{"author":{"id":"U_kgDOB8FKHg","is_bot":false,"login":"shuyiwan","name":"Shuyi Wan"},"headRefName":"Shuyi-PublicHoliday-Controller","number":26,"title":"Added Public Holiday Controller","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/26"},{"author":{"id":"U_kgDOBXmMcA","is_bot":false,"login":"darylou","name":"Daryl Ou"},"headRefName":"Daryl-Location","number":23,"title":"Add Location Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/23"},{"author":{"id":"U_kgDOB8FKHg","is_bot":false,"login":"shuyiwan","name":"Shuyi Wan"},"headRefName":"Shuyi-PublicHoliday","number":22,"title":"Added PublicHoliday Service","url":"https://github.com/ucsb-cs156-f23/team01-f23-6pm-4/pull/22"}]
